Закончил index-header
htmlacademy-htmlcss/360863-device-34 pull request #1
Opened 2022-07-23 22:48 UTC by Leonid-Grishin

2022-07-24 06:17 UTC, Espanol-nikkol requested changes

2022-07-24 06:17 UTC, Espanol-nikkol commented on index.html
> +                            <img class="search-icon" src="images/icons/search.svg" width="16" height="17">
точно контентное изображение?

2022-07-24 06:17 UTC, Espanol-nikkol commented on styles/styles.css
> +img {
по глобальным тегам можно только body и html

2022-07-24 06:17 UTC, Espanol-nikkol commented on index.html
> +                    <div class="tooltip" style="display: none">
![Снимок экрана от 2022-07-24 16-13-05](https://user-images.githubusercontent.com/42237828/180634881-416f38a5-dbc9-4cfa-a089-d7c04aedad00.png)


кхм

2022-07-24 06:17 UTC, Espanol-nikkol commented on index.html
> +                                    <a class="sub-catalog-link active" href="#">Моноподы для селфи</a>
Сделано верно, но это состояние только для страницы каталога "моноподы", класс стоит сейчас убрать, стили оставить

2022-07-24 06:17 UTC, Espanol-nikkol commented on index.html
> +                    <a class="main-navigation-link active" href="#">Доставка</a>
Та же история, что и с моноподами в выпадающем меню

2022-07-24 06:19 UTC, Espanol-nikkol requested changes

2022-07-24 06:19 UTC, Espanol-nikkol commented on .editorconfig
> -indent_size = 2
зачем?

2022-07-24 06:54 UTC, Leonid-Grishin commented on index.html
> +                            <img class="search-icon" src="images/icons/search.svg" width="16" height="17">
нет, не контентное. Просто я не понял как сделать по другому. При добавлении disabled инпуту не получалось сделать opasity для иконки. Вот так только придумал .header-search-input:disabled ~ .search-icon {
    opacity: 0.3;
}
А как еще можно было?

2022-07-24 06:54 UTC, Leonid-Grishin commented on styles/styles.css
> +img {
понял, переделаю

2022-07-24 06:55 UTC, Leonid-Grishin commented on index.html
> +                    <div class="tooltip" style="display: none">
черт)

2022-07-24 06:55 UTC, Leonid-Grishin commented on index.html
> +                    <div class="tooltip" style="display: none">
поправлю, вместе не тестировал

2022-07-24 06:56 UTC, Leonid-Grishin commented on index.html
> +                                    <a class="sub-catalog-link active" href="#">Моноподы для селфи</a>
хорошо

2022-07-24 06:57 UTC, Leonid-Grishin commented on index.html
> +                    <a class="main-navigation-link active" href="#">Доставка</a>
+

2022-07-24 06:57 UTC, Leonid-Grishin commented on .editorconfig
> -indent_size = 2
сам не знаю что нашло) надо 2 оставить как было?

2022-07-24 07:35 UTC, Leonid-Grishin commented on index.html
> +                            <img class="search-icon" src="images/icons/search.svg" width="16" height="17">
переделал

2022-07-27 00:56 UTC, Espanol-nikkol commented on .editorconfig
> -indent_size = 2
+

2022-07-29 14:18 UTC, Espanol-nikkol approved these changes

2022-07-29 14:18 UTC, merged